#!/usr/bin/env python3
# ============================================================
#  import_locales.py
#  PokéRogue GBA - 로케일 데이터 변환 도구
#
#  사용법:
#    python3 tools/pokerogue_import/import_locales.py \
#        --locales /path/to/pokerogue-locales/ko \
#        --output  src/data/rogue/locale_ko.h
#
#  변환 대상:
#    ability.json     → 어빌리티 이름/설명
#    move.json        → 기술 이름/설명
#    pokemon.json     → 포켓몬 이름
#    item.json        → 아이템 이름/설명
#    biome.json       → 바이옴 이름
# ============================================================

import json
import argparse
import re
from pathlib import Path
from typing import Dict, List, Optional

# ── GBA 문자열 인코딩 ─────────────────────────────────────────
# pokeemerald 내부 인코딩으로 변환
# 한글은 extract_korean_chars.py로 별도 처리하므로
# 여기서는 UTF-8 원문을 C 배열로 직렬화

def escape_for_c(s: str, max_len: int = 64) -> str:
    """문자열 → C 문자열 리터럴 (한글 포함 안전 처리)"""
    # pokeemerald 인코딩에서는 한글을 별도 처리하므로
    # 여기서는 구조 생성에 집중하고 실제 변환은 runtime에 수행
    result = []
    for ch in s[:max_len]:
        if ch == '"':
            result.append('\\"')
        elif ch == '\\':
            result.append('\\\\')
        elif ord(ch) < 0x80:
            result.append(ch)
        else:
            # 멀티바이트 한글 → 유니코드 이스케이프 시퀀스
            # GBA에서는 Hangul_ConvertUtf8()로 런타임 변환
            encoded = ch.encode('utf-8')
            result.extend(f"\\x{b:02x}" for b in encoded)
    return ''.join(result)

def sanitize_identifier(name: str) -> str:
    """이름 → C 식별자로 변환"""
    s = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if s and s[0].isdigit():
        s = '_' + s
    return s.upper()


# ── JSON 파서 ─────────────────────────────────────────────────

def load_json(path: Path) -> Optional[dict]:
    if not path.exists():
        print(f"  [SKIP] {path} 없음")
        return None
    try:
        return json.loads(path.read_text(encoding='utf-8'))
    except Exception as e:
        print(f"  [WARN] {path}: {e}")
        return None


def flatten_json(d: dict, prefix: str = "") -> Dict[str, str]:
    """중첩 JSON → 평탄화 {key: value}"""
    result = {}
    for k, v in d.items():
        full_key = f"{prefix}_{k}".strip("_") if prefix else k
        if isinstance(v, dict):
            result.update(flatten_json(v, full_key))
        elif isinstance(v, str):
            result[full_key] = v
    return result


# ── C 헤더 생성 ───────────────────────────────────────────────

def generate_locale_header(locales_dir: Path) -> str:
    lines = []
    lines.append("// AUTO-GENERATED by import_locales.py — DO NOT EDIT")
    lines.append("")
    lines.append("#ifndef LOCALE_KO_H")
    lines.append("#define LOCALE_KO_H")
    lines.append("")
    lines.append("// 한글 로케일 데이터 (UTF-8 → Hangul_ConvertUtf8 런타임 변환)")
    lines.append("")

    # 포켓몬 이름
    pkmn = load_json(locales_dir / "pokemon.json")
    if pkmn:
        flat = flatten_json(pkmn)
        lines.append("// ── 포켓몬 이름 ──────────────────────────────────")
        lines.append(f"#define LOCALE_KO_POKEMON_COUNT {len(flat)}")
        lines.append("static const struct { const char *key; const char *name; }")
        lines.append("gLocaleKoPokemon[] = {")
        for k, v in list(flat.items())[:251]:  # GBA 메모리 제한
            safe_v = escape_for_c(v, 20)
            lines.append(f'    {{ "{k}", "{safe_v}" }},')
        lines.append("};")
        lines.append("")
        print(f"  [+] 포켓몬 이름: {len(flat)}개")

    # 기술 이름
    moves = load_json(locales_dir / "move.json")
    if moves:
        flat = flatten_json(moves)
        name_entries = {k: v for k, v in flat.items() if not k.endswith("_desc")}
        lines.append("// ── 기술 이름 ────────────────────────────────────")
        lines.append(f"#define LOCALE_KO_MOVE_COUNT {len(name_entries)}")
        lines.append("static const struct { const char *key; const char *name; }")
        lines.append("gLocaleKoMoves[] = {")
        for k, v in list(name_entries.items())[:200]:
            safe_v = escape_for_c(v, 16)
            lines.append(f'    {{ "{k}", "{safe_v}" }},')
        lines.append("};")
        lines.append("")
        print(f"  [+] 기술 이름: {len(name_entries)}개")

    # 아이템 이름
    items = load_json(locales_dir / "item.json")
    if items:
        flat = flatten_json(items)
        name_entries = {k: v for k, v in flat.items() if "name" in k.lower()}
        lines.append("// ── 아이템 이름 ──────────────────────────────────")
        lines.append(f"#define LOCALE_KO_ITEM_COUNT {len(name_entries)}")
        lines.append("static const struct { const char *key; const char *name; }")
        lines.append("gLocaleKoItems[] = {")
        for k, v in list(name_entries.items())[:150]:
            safe_v = escape_for_c(v, 20)
            lines.append(f'    {{ "{k}", "{safe_v}" }},')
        lines.append("};")
        lines.append("")
        print(f"  [+] 아이템 이름: {len(name_entries)}개")

    # 바이옴 이름
    biome = load_json(locales_dir / "biome.json")
    if biome:
        flat = flatten_json(biome)
        lines.append("// ── 바이옴 이름 ──────────────────────────────────")
        lines.append("static const struct { const char *key; const char *name; }")
        lines.append("gLocaleKoBiomes[] = {")
        for k, v in flat.items():
            safe_v = escape_for_c(v, 16)
            lines.append(f'    {{ "{k}", "{safe_v}" }},')
        lines.append("};")
        lines.append("")

    lines.append("#endif // LOCALE_KO_H")
    return "\n".join(lines)


# ── 메인 ──────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="PokéRogue 한글 로케일 → GBA C 헤더 변환"
    )
    parser.add_argument("--locales", required=True,
                        help="pokerogue-locales/ko 디렉터리")
    parser.add_argument("--output",  required=True,
                        help="출력 C 헤더 파일 경로")
    args = parser.parse_args()

    locales_path = Path(args.locales)
    out_path     = Path(args.output)

    print(f"[*] 로케일 디렉터리: {locales_path}")

    code = generate_locale_header(locales_path)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(code, encoding="utf-8")
    print(f"[+] 출력: {out_path}")


if __name__ == "__main__":
    main()


# ============================================================
#  import_passives.py  (편의상 여기 포함, 별도 파일로도 사용 가능)
# ============================================================
# 사용법:
#   python3 tools/pokerogue_import/import_passives.py \
#       --pokerogue-src /path/to/pokerogue/src \
#       --output        src/data/rogue/passive_data.generated.h

import sys as _sys

def _passive_main():
    import argparse as _ap
    parser = _ap.ArgumentParser(description="PokéRogue 패시브 데이터 변환")
    parser.add_argument("--pokerogue-src", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    src = Path(args.pokerogue_src)
    out = Path(args.output)

    # PokéRogue 어빌리티 파일 위치
    ability_file = src / "data" / "ability.ts"
    if not ability_file.exists():
        ability_file = src / "data" / "abilities.ts"
    if not ability_file.exists():
        print("[WARN] ability.ts not found. 기본 passive_data.h를 유지합니다.")
        return

    text = ability_file.read_text(encoding="utf-8")

    # 간단한 패턴 추출 (실제로는 더 정교한 파서 필요)
    # Ability.SPEED_BOOST, Ability.DROUGHT, etc.
    ability_pattern = re.compile(r'Abilities\.(\w+)')
    abilities = sorted(set(ability_pattern.findall(text)))

    lines = []
    lines.append("// AUTO-GENERATED by import_passives.py — DO NOT EDIT")
    lines.append("")
    lines.append("// 추출된 어빌리티 목록 (참고용)")
    lines.append(f"// 총 {len(abilities)}개")
    lines.append("// 실제 패시브 구현은 rogue_passive.c 참조")
    lines.append("")
    for ab in abilities[:50]:  # 상위 50개만
        lines.append(f"// Ability.{ab} → PASSIVE_xxx (수동 매핑 필요)")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[+] 패시브 참고 파일 생성: {out}")


if __name__ == "__main__" and "--passive" in _sys.argv:
    _sys.argv.remove("--passive")
    _passive_main()
